import type { Guide } from "../types";

const guide: Guide = {
  slug: "home-care-by-city",
  section: "guides",
  cluster: "finding-care",
  title: "Home Care by City: Agencies, Caregivers and Pay (2026)",
  description:
    "Home care, home health and caregivers in 55 US cities: which county you're in, the state program that pays family, and how to vet a local agency.",
  h1: "Home care by city: finding agencies and caregivers near you",
  short: "Home care by city",
  eyebrow: "55 cities, one method",
  lead: "Whether you're looking for an agency aide in Las Vegas, a home health nurse in Chicago or a way to be paid for caring for your own parent in Houston, the steps are the same. What changes from city to city is the county, the state program and the licensing office. This guide maps all three.",
  answer:
    "To find home care in any US city, start with the county: it decides which Medicaid office, Area Agency on Aging and licensing records apply. Then check the state's program that pays family caregivers, compare licensed local agencies on the state's lookup and Medicare Care Compare, and interview at least three before signing anything.",
  takeaways: [
    "Your **county**, not your city, decides which Medicaid office, Area Agency on Aging and program rules apply.",
    "Home care (help with daily tasks) and home health (skilled nursing and therapy) are different services, paid for differently.",
    "Every state has a Medicaid program that can pay a relative instead of a stranger — often the cheapest option for the family.",
    "Vet agencies on the state license lookup and, for home health, on Medicare Care Compare. We don't rank or list local agencies.",
    "Ask every agency the same questions: licensing, background checks, supervision, backup staff and what the hourly rate includes.",
  ],
  sections: [
    {
      id: "how-to-use",
      h2: "How to use this home care by city guide",
      blocks: [
        "Each city below lists the county it sits in, a link to that county's page, the state program that can pay a family caregiver, and what to check before you hire. We don't publish local agency names, rankings or counts — they change monthly and nobody can verify them from a desk. Instead, we show you where the official records live so you can check any agency yourself.",
        "If you only need the basics, three guides do most of the work: [how to choose a home care agency](/guides/how-to-choose-a-home-care-agency/), [home health vs. home care](/guides/home-health-vs-home-care/) and [home care near me](/guides/home-care-near-me/). New York and Pennsylvania have their own city guides: [home care in New York](/guides/home-care-new-york/) and [home care in Pennsylvania](/guides/home-care-pennsylvania/).",
        {
          table: {
            caption: "The three kinds of help people mean when they search by city",
            head: ["What you search", "What it usually means", "Who usually pays"],
            rows: [
              ["Home care, in-home care, caregivers", "Non-medical help: bathing, dressing, meals, supervision", "Private pay, Medicaid, VA, long-term care insurance"],
              ["Home health, home health care", "Skilled nursing and therapy ordered by a doctor", "Medicare, Medicaid, private insurance"],
              ["Home health aide", "A trained aide, working for either kind of agency", "Depends on the agency and the service"],
            ],
          },
        },
      ],
    },
    {
      id: "vetting",
      h2: "How to find and vet a local home care agency in any city",
      blocks: [
        "The same checklist works in Denver, Miami or Portland. Run it on every agency before anyone comes into the house.",
        {
          ol: [
            "**Confirm the license.** Look the agency up on your state health department's licensing search. Home health agencies are also listed, with quality ratings, on [Medicare Care Compare](https://www.medicare.gov/care-compare/).",
            "**Ask who employs the aide.** An agency that employs its caregivers handles taxes, insurance and backup staff. A registry or referral service may leave you as the employer.",
            "**Ask about screening and training** — background checks, reference checks, and what training aides get before their first shift.",
            "**Ask about supervision.** Who visits to check on care, and how often? Who do you call at 9 p.m. on a Sunday?",
            "**Get the rate in writing,** including minimum shift length, overnight and holiday rates, and mileage.",
            "**Ask whether they take Medicaid** or bill your long-term care insurance, if either applies.",
          ],
        },
        "Your local Area Agency on Aging keeps lists of providers and can explain programs in your county; find it through the federal [Eldercare Locator](https://eldercare.acl.gov/). For a side-by-side of what local agencies do well and where they fall short, see [local home care agencies compared](/compare/local-home-care-agencies/).",
      ],
    },
    {
      id: "nevada",
      h2: "Home health care Las Vegas and Reno: Nevada",
      blocks: [
        { h3: "Las Vegas (Clark County)" },
        "Las Vegas, Henderson and North Las Vegas are all in [Clark County](/nevada/clark/). For home health care, Las Vegas families usually start with a doctor's order and Medicare Care Compare, where every Medicare-certified agency is listed with its star ratings — the closest thing to an official list of home health agencies in Las Vegas. When people search for the best home health care in Las Vegas, those ratings and inspection results are a better guide than ads.",
        "For in home care, Las Vegas agencies offer non-medical help by the hour. Before you sign with any home care agency, Las Vegas or elsewhere in Nevada, check its state license and ask what home care services Las Vegas clients get at its minimum shift. Families comparing home health, Las Vegas agencies and a private caregiver: Las Vegas has all three, and Nevada Medicaid can pay a relative instead.",
        "Nevada pays family caregivers through self-directed **Personal Care Services** and the **Structured Family Caregiving Waiver**, which can pay a spouse. See the [Nevada caregiver program](/nevada/caregiver-program/).",
        { h3: "Reno (Washoe County)" },
        "Reno and Sparks are in [Washoe County](/nevada/washoe/). For home health care, Reno has fewer agencies than Las Vegas, so ask about travel areas and backup staff before you commit. The same Nevada programs apply.",
        { chips: [{ href: "/nevada/clark/", label: "Clark County (Las Vegas)" }, { href: "/nevada/washoe/", label: "Washoe County (Reno)" }, { href: "/nevada/", label: "Nevada" }] },
      ],
    },
    {
      id: "chicago",
      h2: "Home care agency Chicago: Cook County, Illinois",
      blocks: [
        "Chicago is in [Cook County](/illinois/cook/), with suburbs spilling into [DuPage](/illinois/dupage/) and [Lake](/illinois/lake/) counties. It is one of the biggest home care markets in the country, which means lots of choice and lots of variation in quality.",
        { h3: "Home health care Chicago vs. home care Chicago" },
        "Home health care Chicago patients receive after a hospital stay comes from Medicare-certified agencies; you can compare home health agencies Chicago-wide on Medicare Care Compare. Non-medical home care Chicago families pay for by the hour comes from home care agencies. So if someone hands you a list of home care agencies in Chicago, check which kind each one is. The same goes for home health care agencies Chicago hospitals refer you to: you can choose a different one.",
        { h3: "Caregivers Chicago families hire" },
        "Caregiver agencies Chicago families use generally employ the aide; a registry may not. Whether you want home care services Chicago agencies provide, a home health aide Chicago agencies place, or home health Chicago doctors order, ask the vetting questions above before signing with any home care agency Chicago offers. Many caregivers Chicago families rely on are relatives: Illinois can pay them through the **Community Care Program** and **Home Services Program**. See the [Illinois caregiver program](/illinois/caregiver-program/) and [Illinois caregiver pay](/illinois/caregiver-pay/).",
        { chips: [{ href: "/illinois/cook/", label: "Cook County (Chicago)" }, { href: "/illinois/dupage/", label: "DuPage County" }, { href: "/illinois/lake/", label: "Lake County" }] },
      ],
    },
    {
      id: "los-angeles-orange-county",
      h2: "Home care Los Angeles and Orange County, California",
      blocks: [
        { h3: "Los Angeles (Los Angeles County)" },
        "Los Angeles is in [Los Angeles County](/california/los-angeles/), which runs its own IHSS office. For home care Los Angeles families pay privately, you'll find everything from hourly aides to 24 hour home care Los Angeles agencies staff in shifts. Compare in home care services Los Angeles agencies offer by what's included, not just the hourly rate, and check that any home care agency Los Angeles recommends is licensed as a Home Care Organization by the California Department of Social Services.",
        "A home health agency Los Angeles hospitals refer you to is a different thing: skilled care, usually covered by Medicare. Caregivers Los Angeles families hire through a caregiver agency Los Angeles-based are employees of that agency; a home care services Los Angeles registry may leave you as the employer.",
        "California's **IHSS** pays family caregivers, including adult children and, in some cases, spouses. Read our [IHSS guide](/guides/ihss/) and the [California caregiver program](/california/caregiver-program/).",
        { h3: "Orange County" },
        "Orange County (Anaheim, Santa Ana, Irvine) is [Orange County, California](/california/orange/), with its own IHSS office. Home care Orange County families buy privately follows the same rules as LA: pick a licensed home care agency Orange County-based, compare 24 hour home care Orange County quotes on live-in versus shift staffing, and ask each caregiver agency Orange County offers who employs the aide. Many caregivers Orange County families rely on are relatives paid through IHSS. See [24-hour home care](/guides/24-hour-home-care/) and [live-in caregivers](/guides/live-in-caregiver/).",
        { chips: [{ href: "/california/los-angeles/", label: "Los Angeles County" }, { href: "/california/orange/", label: "Orange County, CA" }] },
      ],
    },
    {
      id: "san-diego",
      h2: "Home care San Diego, CA",
      blocks: [
        "San Diego, Chula Vista and Oceanside are in [San Diego County](/california/san-diego/). For home care San Diego families can hire an agency privately or, if the person needing care has Medi-Cal, apply for IHSS through the county.",
        "When you compare a home care agency San Diego-based with a caregiver agency San Diego families mention, ask the same things: license, who employs the caregiver, and backup coverage. A home health aide San Diego agencies send is trained, but what they can do depends on whether they work for a home care or a home health agency. If you'd rather be the paid caregiver, San Diego County's IHSS office is the place to start — see [IHSS](/guides/ihss/).",
        { chips: [{ href: "/california/san-diego/", label: "San Diego County" }, { href: "/california/", label: "California" }] },
      ],
    },
    {
      id: "texas",
      h2: "Home care Houston, Dallas, Fort Worth and San Antonio",
      blocks: [
        "Texas pays family caregivers through **Consumer Directed Services (CDS)** in STAR+PLUS and several waivers, at a reported $15 an hour. Spouses can't be paid, and waivers can have long interest lists. See the [Texas caregiver program](/texas/caregiver-program/) and [Texas caregiver pay](/texas/caregiver-pay/).",
        { h3: "Houston (Harris County)" },
        "Houston is in [Harris County](/texas/harris/). For home care, Houston has a large number of licensed agencies, so vetting matters more than finding one. If you are choosing a home care agency, Houston families can check its license with Texas Health and Human Services, which licenses home and community support services agencies. Many caregivers Houston families rely on are relatives who could be paid through CDS.",
        { h3: "Dallas and Fort Worth" },
        "Dallas is in [Dallas County](/texas/dallas/) and Fort Worth in [Tarrant County](/texas/tarrant/). Some searches name a specific business — \"home care assistance of dallas\" is one people type — but whatever the name, check the license and ask the vetting questions. Caregivers Dallas and caregivers Fort Worth families hire through agencies are employees; family members can be paid through CDS instead.",
        { h3: "San Antonio (Bexar County)" },
        "San Antonio is in [Bexar County](/texas/bexar/). For home care, San Antonio families can compare any home care agency San Antonio-based on the same checklist; home care providers San Antonio families use range from large chains to small local offices. Caregivers in San Antonio, Texas can also be relatives paid through CDS — caregivers in San Antonio who already help a parent should check eligibility first.",
        { chips: [{ href: "/texas/harris/", label: "Harris County (Houston)" }, { href: "/texas/dallas/", label: "Dallas County" }, { href: "/texas/tarrant/", label: "Tarrant County (Fort Worth)" }, { href: "/texas/bexar/", label: "Bexar County (San Antonio)" }] },
      ],
    },
    {
      id: "atlanta",
      h2: "Home care services Atlanta, Georgia",
      blocks: [
        "The city of Atlanta sits mostly in [Fulton County](/georgia/fulton/), with parts in [DeKalb County](/georgia/dekalb/); many families live in [Cobb](/georgia/cobb/) or [Gwinnett](/georgia/gwinnett/).",
        "For home care, Atlanta agencies offer in home care Atlanta families buy by the hour. Home health agencies Atlanta hospitals refer to are Medicare-certified and listed on Care Compare. Whether you want a home care agency Atlanta-wide or a home health aide Atlanta agencies place, the vetting questions are the same, and home care services Atlanta agencies quote should come in writing.",
        "Many caregivers Atlanta families depend on are relatives. Georgia pays live-in family through **Structured Family Caregiving**, at a reported $1,987–$2,400 a month, plus self-directed options in CCSP and SOURCE; waitlists can be long. See [Structured Family Caregiving](/guides/structured-family-caregiving/) and the [Georgia caregiver program](/georgia/caregiver-program/).",
        { chips: [{ href: "/georgia/fulton/", label: "Fulton County" }, { href: "/georgia/dekalb/", label: "DeKalb County" }, { href: "/georgia/cobb/", label: "Cobb County" }, { href: "/georgia/gwinnett/", label: "Gwinnett County" }] },
      ],
    },
    {
      id: "colorado",
      h2: "Home care Denver and Colorado Springs",
      blocks: [
        { h3: "Denver (Denver County)" },
        "Denver is its own county: [Denver County](/colorado/denver/). For home care, Denver agencies need a state license; ask for it. Home health care Denver doctors order comes from Medicare-certified home health agencies Denver hospitals work with; you can compare home health Denver options on Care Compare. Ask any home care agency Denver-based the vetting questions above.",
        "Caregivers Denver families hire don't have to be strangers. Colorado has a program actually called **IHSS**, plus **CDASS**, and both can pay spouses. Reported pay is $17–$20 an hour. See the [Colorado caregiver program](/colorado/caregiver-program/).",
        { h3: "Colorado Springs (El Paso County)" },
        "Colorado Springs is in [El Paso County, Colorado](/colorado/el-paso/). For in home care, Colorado Springs families have the same choices as Denver. People searching \"ihss colorado springs\" are looking for Colorado's In-Home Support Services, which runs through licensed IHSS agencies and lets a relative be the paid caregiver. Caregivers Colorado Springs families hire through CDASS are employed by the member, with payroll handled by a vendor.",
        { chips: [{ href: "/colorado/denver/", label: "Denver County" }, { href: "/colorado/el-paso/", label: "El Paso County (Colorado Springs)" }, { href: "/colorado/arapahoe/", label: "Arapahoe County" }] },
      ],
    },
    {
      id: "indiana",
      h2: "Home health care Indianapolis and Fort Wayne, Indiana",
      blocks: [
        { h3: "Indianapolis (Marion County)" },
        "Indianapolis is in [Marion County, Indiana](/indiana/marion/). Home health care Indianapolis doctors order comes from Medicare-certified home health agencies Indianapolis hospitals refer to; non-medical home care Indianapolis families hire comes from licensed agencies. Compare home care services Indianapolis agencies offer and ask any home care agency Indianapolis-based who employs the aide. A home health aide Indianapolis agencies place may be certified; ask.",
        "Indiana is one of the strongest states for paying relatives. Caregivers Indianapolis families rely on can be paid through **Structured Family Caregiving** (a reported $46–$80 a day for live-in caregivers) or Attendant Care in the PathWays and Health & Wellness waivers. Spouses can be paid. See the [Indiana caregiver program](/indiana/caregiver-program/).",
        { h3: "Fort Wayne (Allen County)" },
        "Fort Wayne is in [Allen County, Indiana](/indiana/allen/). Home care Fort Wayne families arrange follows the same Indiana rules; in home care Fort Wayne agencies provide can also be delivered by a paid family member under SFC.",
        { chips: [{ href: "/indiana/marion/", label: "Marion County (Indianapolis)" }, { href: "/indiana/allen/", label: "Allen County (Fort Wayne)" }] },
      ],
    },
    {
      id: "southwest",
      h2: "Home care Phoenix, Tucson and Albuquerque",
      blocks: [
        { h3: "Phoenix (Maricopa County)" },
        "Phoenix, Mesa, Scottsdale and Glendale are in [Maricopa County](/arizona/maricopa/). For home care, Phoenix has a large senior population and many home care agencies in Phoenix, AZ; compare in home care Phoenix quotes on the checklist. Caregivers Phoenix families rely on can be paid through **ALTCS**, Arizona's long-term care Medicaid, which allows self-directed care, Agency with Choice and paid spouses. See the [Arizona caregiver program](/arizona/caregiver-program/).",
        { h3: "Tucson (Pima County)" },
        "Tucson is in [Pima County](/arizona/pima/). Some searches name a business — \"home care assistance tucson\" is one — but any in home care Tucson agency should pass the same checks. Caregivers in Tucson can be relatives paid through ALTCS.",
        { h3: "Albuquerque (Bernalillo County)" },
        "Albuquerque is in [Bernalillo County](/new-mexico/bernalillo/). Home care Albuquerque families arrange through Medicaid runs through Turquoise Care's Self-Directed Community Benefit or the Mi Via Waiver, both of which can pay relatives, including spouses. Caregivers Albuquerque families hire privately should come through a licensed agency. See the [New Mexico caregiver program](/new-mexico/caregiver-program/).",
        { chips: [{ href: "/arizona/maricopa/", label: "Maricopa County (Phoenix)" }, { href: "/arizona/pima/", label: "Pima County (Tucson)" }, { href: "/new-mexico/bernalillo/", label: "Bernalillo County (Albuquerque)" }] },
      ],
    },
    {
      id: "central-florida",
      h2: "Home care in Orlando, Florida, Tampa and The Villages",
      blocks: [
        "Florida pays relatives through the **Participant Directed Option** in Statewide Medicaid Managed Care Long-Term Care and through **CDC+**. The long-term care program often has a long waitlist, so apply early. See the [Florida caregiver program](/florida/caregiver-program/) and [Florida caregiver pay](/florida/caregiver-pay/).",
        { h3: "Orlando (Orange County)" },
        "Orlando is in [Orange County, Florida](/florida/orange/). Home care Orlando families buy privately comes from agencies licensed by Florida's Agency for Health Care Administration (AHCA); ask any home care agency Orlando-based for its license number. In home care Orlando agencies provide may be delivered by a home health aide Orlando agencies train, or by a companion; ask which.",
        { h3: "Tampa and St. Petersburg" },
        "Tampa is in [Hillsborough County](/florida/hillsborough/) and St. Petersburg in [Pinellas County](/florida/pinellas/). Home care Tampa families arrange and home care St. Petersburg, FL families arrange follow the same AHCA licensing and Medicaid rules.",
        { h3: "The Villages (Sumter County)" },
        "Most of The Villages is in [Sumter County](/florida/sumter/), with parts in Lake and Marion counties. In home care The Villages, FL residents use is often private pay; check the license and whether the agency will cover all three counties.",
        { chips: [{ href: "/florida/orange/", label: "Orange County (Orlando)" }, { href: "/florida/hillsborough/", label: "Hillsborough County (Tampa)" }, { href: "/florida/pinellas/", label: "Pinellas County (St. Petersburg)" }, { href: "/florida/sumter/", label: "Sumter County (The Villages)" }] },
      ],
    },
    {
      id: "south-florida",
      h2: "Home care Miami, Fort Lauderdale and West Palm Beach",
      blocks: [
        { h3: "Miami (Miami-Dade County)" },
        "Miami is in [Miami-Dade County](/florida/miami-dade/). For home care, Miami has many agencies and many registries — know which you're hiring. Ask any home care agency Miami-based whether a home health aide Miami clients receive is its employee or an independent contractor.",
        { h3: "Fort Lauderdale (Broward County)" },
        "Fort Lauderdale is in [Broward County](/florida/broward/). Home care Fort Lauderdale families buy, and a home health aide Fort Lauderdale agencies send, are covered by the same AHCA licensing.",
        { h3: "West Palm Beach (Palm Beach County)" },
        "West Palm Beach is in [Palm Beach County](/florida/palm-beach/). Home health agencies West Palm Beach hospitals refer to are listed on Medicare Care Compare; home health care West Palm Beach patients receive after surgery is usually Medicare-covered and short-term. Home care West Palm Beach families pay for privately is a different service. If you're comparing home health, West Palm Beach agencies' star ratings are public; ask what a home health aide West Palm Beach agencies send can and can't do.",
        { chips: [{ href: "/florida/miami-dade/", label: "Miami-Dade County" }, { href: "/florida/broward/", label: "Broward County (Fort Lauderdale)" }, { href: "/florida/palm-beach/", label: "Palm Beach County" }] },
      ],
    },
    {
      id: "new-england",
      h2: "Home care Boston, Springfield, Hartford and Portland, Maine",
      blocks: [
        { h3: "Boston (Suffolk County)" },
        "Boston is in [Suffolk County, Massachusetts](/massachusetts/suffolk/). For home care, Boston families should ask any home care agency Boston-based about its license, and what a home health aide Boston clients get is trained to do. Massachusetts pays relatives other than spouses through the **PCA Program** and **Adult Foster Care**. See the [Massachusetts caregiver program](/massachusetts/caregiver-program/).",
        { h3: "Springfield (Hampden County)" },
        "Home care agencies Springfield, MA families use fall under the same Massachusetts rules; Springfield is in [Hampden County](/massachusetts/hampden/).",
        { h3: "Hartford, Connecticut" },
        "Connecticut replaced counties with planning regions; Hartford is in the [Capitol Planning Region](/connecticut/capitol-planning-region/). Ask home care agencies Hartford, CT families consider how the state licenses or registers them. Connecticut pays relatives through Community First Choice, Adult Family Living and the CT Home Care Program. See the [Connecticut caregiver program](/connecticut/caregiver-program/).",
        { h3: "Portland, Maine (Cumberland County)" },
        "Home care Portland, Maine families arrange falls under Maine's rules; Portland is in [Cumberland County, Maine](/maine/cumberland/). Maine pays relatives through Consumer Directed Attendant Services. See the [Maine caregiver program](/maine/caregiver-program/).",
        { chips: [{ href: "/massachusetts/suffolk/", label: "Suffolk County (Boston)" }, { href: "/massachusetts/hampden/", label: "Hampden County (Springfield)" }, { href: "/connecticut/capitol-planning-region/", label: "Capitol Region (Hartford)" }, { href: "/maine/cumberland/", label: "Cumberland County, ME" }] },
      ],
    },
    {
      id: "mid-atlantic",
      h2: "Home care agency Baltimore, Wilmington, Newark and Richmond",
      blocks: [
        { h3: "Baltimore" },
        "Baltimore City is its own jurisdiction — [Baltimore City](/maryland/baltimore-city/) — separate from [Baltimore County](/maryland/baltimore-county/). Ask any home care agency Baltimore families consider for its Maryland license, and ask whether a home health aide Baltimore clients receive is a certified nursing assistant. For respite care, Baltimore families can start with the city or county Area Agency on Aging; see [respite care](/guides/respite-care/). Maryland pays relatives, including spouses, through Community First Choice and the Community Options Waiver. See the [Maryland caregiver program](/maryland/caregiver-program/).",
        { h3: "Wilmington, Delaware (New Castle County)" },
        "Home care Wilmington, DE families arrange falls under Delaware's rules; Wilmington is in [New Castle County](/delaware/new-castle/). Delaware pays relatives, including spouses, through self-directed care in DSHP-Plus.",
        { h3: "Newark and Jersey City, New Jersey" },
        "Newark is in [Essex County, New Jersey](/new-jersey/essex/) and Jersey City in [Hudson County](/new-jersey/hudson/). Home care agencies Newark, NJ families hire, and any home health aide agency Jersey City families use, should show you their New Jersey license or registration; ask to see it. New Jersey pays relatives, including spouses, through the **Personal Preference Program**. See the [New Jersey caregiver program](/new-jersey/caregiver-program/).",
        { h3: "Richmond, Virginia" },
        "Richmond city is its own jurisdiction — [Richmond city](/virginia/richmond-city/) — next to [Henrico County](/virginia/henrico/). For home care, Richmond families on Medicaid can use consumer direction in the CCC Plus Waiver. See the [Virginia caregiver program](/virginia/caregiver-program/).",
        { chips: [{ href: "/maryland/baltimore-city/", label: "Baltimore City" }, { href: "/delaware/new-castle/", label: "New Castle County (Wilmington)" }, { href: "/new-jersey/essex/", label: "Essex County (Newark)" }, { href: "/new-jersey/hudson/", label: "Hudson County (Jersey City)" }, { href: "/virginia/richmond-city/", label: "Richmond city" }] },
      ],
    },
    {
      id: "carolinas",
      h2: "Home care Charlotte, NC, Raleigh and Columbia, SC",
      blocks: [
        { h3: "Charlotte (Mecklenburg County)" },
        "Charlotte is in [Mecklenburg County, North Carolina](/north-carolina/mecklenburg/). Ask any home care agency Charlotte, NC families consider for its North Carolina license. Caregivers Charlotte, NC families hire through agencies and a home health aide Charlotte, NC agencies send should both have passed background checks. North Carolina pays relatives, including spouses, through consumer-directed CAP/DA. See the [North Carolina caregiver program](/north-carolina/caregiver-program/).",
        { h3: "Raleigh (Wake County)" },
        "Raleigh is in [Wake County](/north-carolina/wake/). In home care Raleigh, NC families arrange and a home health aide Raleigh, NC agencies place follow the same North Carolina rules.",
        { h3: "Columbia and Charleston, South Carolina" },
        "Columbia is in [Richland County](/south-carolina/richland/) and Charleston in [Charleston County](/south-carolina/charleston/). Home care Columbia, SC families arrange privately and in home care Columbia, SC Medicaid pays for are different routes. Caregivers Columbia, SC and caregivers Charleston, SC families already rely on may be paid through the self-directed Community Choices Waiver. See the [South Carolina caregiver program](/south-carolina/caregiver-program/).",
        { chips: [{ href: "/north-carolina/mecklenburg/", label: "Mecklenburg County (Charlotte)" }, { href: "/north-carolina/wake/", label: "Wake County (Raleigh)" }, { href: "/south-carolina/richland/", label: "Richland County (Columbia)" }, { href: "/south-carolina/charleston/", label: "Charleston County" }] },
      ],
    },
    {
      id: "ohio-kentucky-tennessee",
      h2: "Home care Columbus, Ohio, Louisville and Nashville",
      blocks: [
        { h3: "Columbus and Cleveland, Ohio" },
        "Columbus is in [Franklin County, Ohio](/ohio/franklin/) and Cleveland in [Cuyahoga County](/ohio/cuyahoga/). For home care, Columbus, Ohio families can use PASSPORT or Ohio's Structured Family Caregiving; a home health aide Columbus, Ohio agencies place, or a home health aide Cleveland agencies place, can also be a relative hired through self-direction. Caregivers Columbus, Ohio families rely on, spouses included, can be paid. See the [Ohio caregiver program](/ohio/caregiver-program/).",
        { h3: "Louisville, Kentucky (Jefferson County)" },
        "Louisville is in [Jefferson County, Kentucky](/kentucky/jefferson/). In home care Louisville, KY families arrange through Medicaid can include **Participant Directed Services**, which reports the highest hourly rate in our data at $29.04. Caregivers Louisville, KY families rely on — spouses included — can be paid, though waivers have waitlists. For respite care, Louisville, KY families can ask the Area Agency on Aging. See the [Kentucky caregiver program](/kentucky/caregiver-program/).",
        { h3: "Nashville and Memphis, Tennessee" },
        "Nashville is in [Davidson County](/tennessee/davidson/) and Memphis in [Shelby County, Tennessee](/tennessee/shelby/). Home care Nashville families arrange through TennCare CHOICES can use consumer direction; caregivers Nashville families rely on, and any caregiver Memphis, TN families hire this way, can be relatives other than spouses. See the [Tennessee caregiver program](/tennessee/caregiver-program/).",
        { chips: [{ href: "/ohio/franklin/", label: "Franklin County (Columbus)" }, { href: "/ohio/cuyahoga/", label: "Cuyahoga County (Cleveland)" }, { href: "/kentucky/jefferson/", label: "Jefferson County (Louisville)" }, { href: "/tennessee/davidson/", label: "Davidson County (Nashville)" }, { href: "/tennessee/shelby/", label: "Shelby County (Memphis)" }] },
      ],
    },
    {
      id: "midwest",
      h2: "Home care Kansas City, St. Louis, Wichita and Minneapolis",
      blocks: [
        { h3: "Kansas City" },
        "Kansas City, Missouri is mostly in [Jackson County, Missouri](/missouri/jackson/); Kansas City, Kansas is in [Wyandotte County](/kansas/wyandotte/). Home care Kansas City families arrange depends on which side of State Line Road the person lives on. Home health care Kansas City hospitals order is Medicare-covered either way; in home care Kansas City Medicaid pays for runs through Missouri's Consumer Directed Services or Kansas's Frail Elderly and Physical Disability waivers.",
        { h3: "St. Louis and St. Charles" },
        "St. Louis city — [St. Louis city](/missouri/st-louis-city/) — is separate from [St. Louis County](/missouri/st-louis-county/); St. Charles is in [St. Charles County](/missouri/st-charles/). Home care St. Louis families buy is often private home care; St. Louis agencies should still be licensed by the state. \"Assistance home care st louis\" and \"assistance home care st charles\" are phrases people type when looking for help with daily tasks. Caregivers St. Louis families rely on can be paid through **Consumer Directed Services**. See the [Missouri caregiver program](/missouri/caregiver-program/).",
        { h3: "Wichita, Kansas (Sedgwick County)" },
        "Caregivers Wichita, KS families rely on can be paid, spouses included, through the Kansas waivers; Wichita is in [Sedgwick County, Kansas](/kansas/sedgwick/). See the [Kansas caregiver program](/kansas/caregiver-program/).",
        { h3: "Minneapolis (Hennepin County)" },
        "Home care Minneapolis families arrange through Minnesota's CFSS or CDCS can pay a relative, including a spouse, at a reported $22.74 an hour; Minneapolis is in [Hennepin County](/minnesota/hennepin/). See the [Minnesota caregiver program](/minnesota/caregiver-program/).",
        { h3: "Little Rock, Arkansas (Pulaski County)" },
        "Home health care Little Rock doctors order is Medicare-covered; ongoing help at home can be self-directed through IndependentChoices. Little Rock is in [Pulaski County, Arkansas](/arkansas/pulaski/). See the [Arkansas caregiver program](/arkansas/caregiver-program/).",
        { chips: [{ href: "/missouri/jackson/", label: "Jackson County, MO" }, { href: "/kansas/wyandotte/", label: "Wyandotte County, KS" }, { href: "/missouri/st-louis-city/", label: "St. Louis city" }, { href: "/missouri/st-charles/", label: "St. Charles County" }, { href: "/kansas/sedgwick/", label: "Sedgwick County (Wichita)" }, { href: "/minnesota/hennepin/", label: "Hennepin County" }, { href: "/arkansas/pulaski/", label: "Pulaski County (Little Rock)" }] },
      ],
    },
    {
      id: "pacific-northwest",
      h2: "In home care Portland, Oregon, Salem and the Northwest",
      blocks: [
        "Oregon is one of the easiest states to be paid as a family caregiver: the Consumer-Employed Provider program and Independent Choices can pay relatives, and there's a Spousal Pay Program. Reported pay is $20–$24.10 an hour. See the [Oregon caregiver program](/oregon/caregiver-program/).",
        { h3: "Portland (Multnomah County)" },
        "Portland is mostly in [Multnomah County](/oregon/multnomah/), with suburbs in [Washington](/oregon/washington/) and [Clackamas](/oregon/clackamas/) counties. For Portland in home care, compare licensed in-home care agencies with a homecare worker hired directly; in home care Portland families arrange through Medicaid often uses the second. A caregiver Portland, Oregon families hire directly can be a relative.",
        { h3: "Salem and Bend" },
        "Salem is in [Marion County, Oregon](/oregon/marion/) and Bend in [Deschutes County](/oregon/deschutes/). Home care Salem, Oregon families arrange, in home care Salem, Oregon Medicaid pays for, caregivers Salem, Oregon families hire and in home care Bend, Oregon residents use all follow the same state rules.",
        { h3: "Vancouver, Spokane and Bellevue, Washington" },
        "Vancouver, Washington is in [Clark County, Washington](/washington/clark/); for private home care, Vancouver families should check the agency's Washington state license. Caregivers Vancouver, WA families rely on can be relatives paid as Individual Providers. Home care Spokane families arrange ([Spokane County](/washington/spokane/)) and in home care Bellevue families arrange ([King County](/washington/king/)) follow the same rules. Washington does not pay spouses. See the [Washington caregiver program](/washington/caregiver-program/).",
        "One note: some searches, like \"live in care agencies in london\", are for the UK. We only cover US programs; UK readers should contact their local council.",
        { chips: [{ href: "/oregon/multnomah/", label: "Multnomah County (Portland)" }, { href: "/oregon/marion/", label: "Marion County (Salem)" }, { href: "/oregon/deschutes/", label: "Deschutes County (Bend)" }, { href: "/washington/clark/", label: "Clark County (Vancouver)" }, { href: "/washington/spokane/", label: "Spokane County" }, { href: "/washington/king/", label: "King County (Bellevue)" }] },
      ],
    },
    {
      id: "paid-family",
      h2: "In every city: your relative's care can pay you",
      blocks: [
        "Private home care is expensive in every big city, and Medicare doesn't pay for ongoing daily help — see [does Medicare pay family caregivers](/guides/does-medicare-pay-family-caregivers/). If the person who needs care qualifies for Medicaid, the same hours an agency would bill can often be paid to you instead. That's true in all 50 states and DC.",
        { stateTable: "programs" },
        "Start with [how to get paid to care for a family member](/guides/get-paid-to-care-for-family-member/), compare [family caregiver pay rates](/guides/family-caregiver-pay-rates/), or [check eligibility in two minutes](/qualify/). If an agency route suits you better, see [home care agencies that hire family members](/guides/home-care-agencies-that-hire-family-members/).",
      ],
    },
    {
      id: "costs",
      h2: "What home care costs in big cities",
      blocks: [
        "Hourly rates vary by metro, by agency and by what's included. We don't publish city rates we can't verify; the national survey figures and how to budget for them are in [the cost of in-home care](/guides/cost-of-in-home-care/). For private arrangements, see [private pay home care](/guides/private-pay-home-care/); for round-the-clock needs, [24-hour home care](/guides/24-hour-home-care/).",
        {
          callout: {
            tone: "money",
            title: "Before you pay privately",
            text: "Check Medicaid eligibility first. Long-term care Medicaid has different rules from regular Medicaid, and many families who assume they earn too much turn out to qualify. See [Medicaid home care](/guides/medicaid-home-care/).",
          },
        },
      ],
    },
    {
      id: "next-steps",
      h2: "Where to go next",
      blocks: [
        {
          cards: [
            { href: "/qualify/", title: "Check eligibility", text: "Five questions, your state's programs and pay range." },
            { href: "/guides/how-to-choose-a-home-care-agency/", title: "Choose an agency", text: "The questions to ask before you sign." },
            { href: "/guides/home-care-new-york/", title: "Home care in New York", text: "NYC boroughs, Long Island, Buffalo, Rochester and CDPAP." },
            { href: "/guides/home-care-pennsylvania/", title: "Home care in Pennsylvania", text: "Philadelphia, Pittsburgh and paid family care in PA." },
          ],
        },
      ],
    },
  ],
  faqs: [
    {
      q: "How do I find a licensed home care agency in my city?",
      a: "Look the agency up on your state health department's license search. For Medicare-certified home health agencies, use Medicare Care Compare, which shows star ratings and inspection results by ZIP code.",
    },
    {
      q: "Why does my county matter more than my city?",
      a: "Medicaid applications, Area Agencies on Aging and many program offices are organized by county. Knowing your county tells you which office handles your relative's case.",
    },
    {
      q: "What's the difference between home care and home health care?",
      a: "Home care is non-medical help with daily tasks like bathing and meals. Home health care is skilled nursing or therapy ordered by a doctor, usually short-term and often paid by Medicare.",
    },
    {
      q: "Can a family member be the paid caregiver instead of an agency?",
      a: "Yes. Every state has at least one Medicaid program that can pay a relative. Spouse rules vary by state, so check your state's caregiver program page.",
    },
    {
      q: "Do you recommend specific agencies in each city?",
      a: "No. We don't rank or list local agencies. We show you where official license and quality records live so you can check any agency yourself.",
    },
    {
      q: "Does Medicare pay for home care in my city?",
      a: "Medicare pays for short-term skilled home health care when a doctor orders it and you're homebound. It does not pay for ongoing non-medical help or for family caregivers.",
    },
    {
      q: "Is Sunroom Care a home care agency?",
      a: "No. Sunroom Care is not an agency and not a state office. We help families find the program that pays a relative and handle the enrollment paperwork, free to the family.",
    },
  ],
  related: [
    "/guides/home-care-near-me/",
    "/guides/how-to-choose-a-home-care-agency/",
    "/guides/home-care-new-york/",
  ],
  sources: [
    { label: "Medicare Care Compare: home health agencies", url: "https://www.medicare.gov/care-compare/" },
    { label: "Eldercare Locator (Administration for Community Living)", url: "https://eldercare.acl.gov/" },
    { label: "Medicaid.gov: self-directed services", url: "https://www.medicaid.gov/medicaid/long-term-services-supports/self-directed-services" },
    { label: "Each state's published Medicaid program rules", url: "https://www.medicaid.gov/state-overviews/index.html" },
  ],
  published: "2026-09-30",
  updated: "2026-09-30",
  photo: { src: "/photos/caregiver-phone.webp", alt: "A caregiver checks her phone while planning the day's visits" },
  keywords: [
    "home health care las vegas",
    "home care services las vegas",
    "home health care indianapolis",
    "home care services atlanta",
    "home care san diego",
    "home care denver",
    "home health care denver",
    "home health las vegas",
    "home care agency houston",
    "home care columbus ohio",
    "home care indianapolis",
    "home care atlanta",
    "home health denver",
    "home care san antonio",
    "home care houston",
    "home care san diego ca",
    "in home care las vegas",
    "caregiver las vegas",
    "home care agency chicago",
    "caregivers los angeles",
  ],
};

export default guide;
